name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Laravel Environment
        uses: ./.github/actions/setup-laravel
        env:
          FATHOM_SITE: ${{ secrets.FATHOM_SITE }}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}
          ALGOLIA_SECRET: ${{ secrets.ALGOLIA_SECRET }}
          NIGHTWATCH_TOKEN: ${{ secrets.NIGHTWATCH_TOKEN }}

      - name: Fire up Nightwatch agent
        run: |
          php artisan nightwatch:agent &
          sleep 5

      - name: Gather beer data
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
        run: php artisan roach:run IndySpider

      - name: Refresh search index
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
        run: |
          php artisan scout:flush 'App\Models\Beer'
          php artisan scout:import 'App\Models\Beer'

      - name: Generate static site
        run: php artisan export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
